#!/bin/bash
# Thanks to junegunn

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl --insecure -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf $BASE/vimrc ~/.vimrc

# nvim
mkdir -p ~/.config/nvim/autoload
ln -sf $BASE/vimrc ~/.config/nvim/init.vim
ln -sf ~/.vim/autoload/plug.vim ~/.config/nvim/autoload/

mkdir -p ~/.config/nvim
ln -sf $BASE/coc-settings.json ~/.config/nvim/coc-settings.json

vim +PlugInstall +qall

# fonts
curl -fLo ~/.local/share/fonts/D2CodingLigatureNerdMono.ttf --create-dirs https://github.com/gwanryo/d2coding-nerd/raw/main/D2CodingLigatureNerdMono.ttf
fc-cache -f -v

# neovim
python3 -m pip install pynvim
npm install -g neovim
gem install neovim
